local OX_INVENTORY_RESOURCE_NAME <const> = 'ox_inventory'
local RESOURCE_PATH <const> = GetResourcePath(OX_INVENTORY_RESOURCE_NAME)
if not RESOURCE_PATH then
    error(string.format("%s resource not found. Please ensure %s is present in your resource folder. If you have renamed ox_inventory please update the OX_INVENTORY_RESOURCE_NAME variable in server.lua", OX_INVENTORY_RESOURCE_NAME, OX_INVENTORY_RESOURCE_NAME))
end

local IMAGES_FOLDER <const> = RESOURCE_PATH..'/web/images'

-- Valid image file extensions
local IMAGE_EXTENSIONS <const> = {
    png = true,
    jpg = true,
    jpeg = true,
    apng = true,
    webp = true
}

-- Unused images that should be ignored by the script.
-- Some items are generated by ox_inventory during runtime, hence there are images here by default.
-- See: https://github.com/CommunityOx/ox_inventory/blob/8968c10a4396676996ad352c1241af9d1f7ea9d0/modules/items/server.lua#L12
local IGNORE_UNUSED_IMAGES <const> = {
    ['trash_burger.png'] = true,
    ['trash_can.png'] = true,
    ['trash_bread.png'] = true,
    ['trash_chips.png'] = true,
    ['panties.png'] = true,
    ['WEAPON_ACIDPACKAGE.png'] = true
}

-- Missing item images that should be ignored by the script.
-- 'cash' is hardcoded in ox_inventory to be the same as 'money', hence it might lack an image, but that is okay, so we ignore it.
local IGNORE_MISSING_IMAGES <const> = {
    ['cash'] = true
}

---Loads a resource file provided the file path
---@param resourceName string The resource to load the file from
---@param filePath string
---@return any
local function loadFile(resourceName, filePath)
    local file = LoadResourceFile(resourceName, filePath)
    local path = string.format('%s/%s', resourceName, filePath)

    if not file then
        error(string.format("No file was found with path %s", path))
    end

    local func, err = load(file, path)
    if not func or err then
        error(err, 0)
    end

    return func()
end

---Gathers all the items from ox_inventory
---@return table
local function getItems()
    -- We load the item files instead of using exports so we can read the client image data   
    local itemsFile = loadFile(OX_INVENTORY_RESOURCE_NAME, 'data/items.lua')
    local weaponsFile = loadFile(OX_INVENTORY_RESOURCE_NAME, 'data/weapons.lua')

    local items = {}
    for name, item in pairs(itemsFile) do
        items[name] = item
    end

    for name, item in pairs(weaponsFile.Weapons) do
        items[name] = item
    end

    for name, item in pairs(weaponsFile.Components) do
        items[name] = item
    end

    for name, item in pairs(weaponsFile.Ammo) do
        items[name] = item
    end

    return items
end

---Returns all of the item's images
---@return table
local function getItemImages()
    local items = getItems()
    local itemImages = {}

    for name, item in pairs(items) do
        if item?.client?.image then
            itemImages[name] = item.client.image:gsub('%.%w+$', '')
        else
            itemImages[name] = name
        end
    end

    return itemImages
end

---Returns all the image files
---@return table? imageFiles
local function getItemImageFiles()
    local imageFolder = io.popen('dir "'..IMAGES_FOLDER..'" /b')
    if not imageFolder then
        return print("ERROR: Unable to access images folder at: "..IMAGES_FOLDER)
    end

    local imageFiles = {}
    for imageFile in imageFolder:lines() do
        local imageName = imageFile:gsub('%.%w+$', '')
        local extension = imageFile:match('%.([^.]+)$')

        if IMAGE_EXTENSIONS[extension] then
            if not imageFiles[imageName] then
                imageFiles[imageName] = imageFile
            end
        elseif extension then
            if IMAGE_EXTENSIONS[extension:lower()] then
                print(string.format("Image file '%s' has an invalid image extension variation (%s). ox_inventory does not support uppercase extensions.", imageFile, extension))
            else
                print(string.format("Ignoring file '%s' as it does not have a valid image extension (%s). Is this file even supposed to be here?", imageFile, extension))
            end
        end
    end

    imageFolder:close()
    return imageFiles
end

---Gets all the missing images
---@param itemImages table
---@param imageFiles table
---@return integer count
---@return table missingImages
local function getMissingImages(itemImages, imageFiles)
    local missingCount = 0
    local missingImages = {}

    for itemName, imageName in pairs(itemImages) do
        if not imageFiles[imageName] and not IGNORE_MISSING_IMAGES[itemName] then
            missingCount += 1
            missingImages[missingCount] = imageName
        end
    end

    return missingCount, missingImages
end

---Gets all the unused images
---@param itemImages table
---@param imageFiles table
---@return integer count
---@return table unusedImages
local function getUnusedImages(itemImages, imageFiles)
    local unusedCount = 0
    local unusedImages = {}

    local usedImages = {}
    for _itemName, imageName in pairs(itemImages) do
        usedImages[imageName] = true
    end

    for _itemName, imageFile in pairs(imageFiles) do
        local imageName = imageFile:gsub('%.%w+$', '')
        if not usedImages[imageName] and not IGNORE_UNUSED_IMAGES[imageFile] then
            unusedCount += 1
            unusedImages[unusedCount] = imageFile
        end
    end

    return unusedCount, unusedImages
end

---Deletes all the passed images
---@param unusedImages table
local function deleteImages(unusedImages)
    local deletedCount = 0

    for _index, imageFile in pairs(unusedImages) do
        local success, err = os.remove(IMAGES_FOLDER..'/'..imageFile)
        if success then
            deletedCount = deletedCount + 1
            print("Deleted "..imageFile)
        else
            print("ERROR deleting "..imageFile, err)
        end
    end

    print("Cleanup complete. Deleted "..deletedCount.." images!")
end

RegisterCommand('validate_inventory_images', function(source, args, raw)
    if source ~= 0 then return end -- Only allow server console to run this command

    local itemImages = getItemImages()
    local imageFiles = getItemImageFiles()
    if not imageFiles then return end

    local missingCount, missingImages = getMissingImages(itemImages, imageFiles)
    local unusedCount, unusedImages = getUnusedImages(itemImages, imageFiles)

    if missingCount <= 0 then
        print("No items with missing images found.")
    else
        print(string.format("Found %d items with missing images:", missingCount))
        for _index, imageName in pairs(missingImages) do
            print("  "..imageName)
        end
    end

    if unusedCount <= 0 then
        print("No unused images found.")
    else
        print(string.format("Found %d unused images:", unusedCount))
        for _index, imageName in pairs(unusedImages) do
            print("  "..imageName)
        end

        print("Run the 'cleanup_inventory_images' command to delete the unused images.")
    end
end, true)

RegisterCommand('cleanup_inventory_images', function(source, args, raw)
    if source ~= 0 then return end -- Only allow server console to run this command

    local itemImages = getItemImages()
    local imageFiles = getItemImageFiles()
    if not imageFiles then return end

    local unusedCount, unusedImages = getUnusedImages(itemImages, imageFiles)

    if unusedCount <= 0 then
        return print("No unused images found. Cleanup not required.")
    end

    deleteImages(unusedImages)
end, true)
